---

- name: setup playbook
  hosts: ios_builders
  remote_user: administrator
  become: false
  gather_facts: true

  roles:
    - brew
    - role: ruby
      vars:
        ruby:
          version: 2.7.2
    - bundler
    # - role: xcversion
    #   vars:
    #     xcode:
    #       versions:
    #         - "12.3"

  tasks:
    - homebrew:
        name: jq
        state: present
