---
# tasks file for ruby

- name: "Install rbenv"
  community.general.homebrew:
    name:
      - rbenv
      - ruby-build
    state: present

- name: "ensure rbenv is in bash PATH"
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bash_profile"
    line: "{{ item }}"
    mode: 0755
    create: true
  when: lookup('env', 'SHELL') == '/bin/bash'
  loop:
    - "eval $(rbenv init -)"
    - 'export PATH="$HOME/.rbenv/bin:$PATH"'

- name: "ensure rbenv is in zsh PATH"
  lineinfile:
    path: "{{ ansible_env.HOME }}/.zprofile"
    line: "{{ item }}"
    mode: 0755
    create: true
  when: lookup('env', 'SHELL') == '/bin/zsh'
  loop:
    - "eval \"$(rbenv init -)\""
    - 'export PATH="$HOME/.rbenv/bin:$PATH"'

- name: "Select ruby version"
  command: "{{ansible_user_shell}} -l -c 'rbenv global {{ ruby.version }}'"
  register: correct_ruby_version
  ignore_errors: true

- name: "Install ruby version"
  command: "{{ansible_user_shell}} -l -c 'rbenv install {{ ruby.version }}'"
  register: installed_ruby_version
  when: correct_ruby_version.rc == 1

- name: "Select installed ruby version"
  command: "{{ansible_user_shell}} -l -c 'rbenv global {{ ruby.version }}'"
  when:
    - correct_ruby_version.rc == 1
    - installed_ruby_version.rc == 0

